spring.application.name=email-indexer
spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}
app.dataset.path=${DATASET_PATH:d:/Formation/Wevops/Elastic Stack/Elastic-Dev/data/emails_dataset.json}

logging.level.org.springframework.data.elasticsearch.client.WIRE=TRACE
